apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  namespace: dev
  labels:
    app: wil-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - name: wil-playground
        image: wil42/playground:v2
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: wil-playground
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil-playground-ingress
  namespace: dev
spec:
  rules:
  - host: wilS.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wil-playground-service
            port:
              number: 80
